---
- hosts: all
  remote_user: vagrant
  vars:
    iptables_bottom: "^-A INPUT -j REJECT --reject-with icmp-host-prohibited"

  tasks:
    - name: Install common packages
      yum: name={{ item }} state=present
      with_items:
        - java-1.7.0-openjdk-1.7.0.71
        - java-1.7.0-openjdk-devel-1.7.0.71
      sudo: yes

    # move to separate file
    - name: iptables allow JBoss ports
      lineinfile:
        dest=/etc/sysconfig/iptables
        state=present
        regexp="^.*INPUT.*NEW.*tcp.*port {{ item }} -j ACCEPT"
        insertbefore="{{ iptables_bottom }}"
        line="-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ item }} -j ACCEPT"
      with_items:
        - 8080
        - 8443
        - 9990
        - 9443
      sudo: yes
      notify: restart iptables

  handlers:
    - name: restart iptables
      service: name=iptables state=restarted
      sudo: yes
