---
- hosts: all
  remote_user: vagrant

  tasks:
    - name: Install common packages
      yum: name={{ item }} state=present
      with_items:
        - java-1.7.0-openjdk-1.7.0.75
        - java-1.7.0-openjdk-devel-1.7.0.75
      sudo: yes

    - name: disable iptables
      service: name=iptables state=stopped enabled=no
      sudo: yes

