---
- hosts: all
  remote_user: vagrant
  tasks:
    - name: Copy deployment archive and unpack
      unarchive: src=deploy-pkg/deployment.zip dest=/home/vagrant/xfer

    - name: Verify JBoss is running
      service: name=jboss state=started
      sudo: yes

    - name: Deploy artifacts
      shell: /home/vagrant/jboss/jboss-eap-6.3/bin/jboss-cli.sh -c "deploy --force /home/vagrant/xfer/artifacts/jboss-helloworld.war"

